# Generated by Django 2.0 on 2017-12-26 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorterner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mirkan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=200, unique=True)),
                ('soyad', models.CharField(max_length=200, unique=True)),
            ],
        ),
    ]
