# Generated by Django 2.0 on 2017-12-27 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorterner', '0002_mirkan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kirrurl',
            name='shortcode',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='mirkan',
            name='isim',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='mirkan',
            name='soyad',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
