# Generated by Django 2.0 on 2017-12-27 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorterner', '0003_auto_20171227_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='kirrurl',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
