# Generated by Django 2.0 on 2017-12-27 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorterner', '0004_kirrurl_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='mirkan',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
