# Generated by Django 2.0 on 2017-12-28 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorterner', '0005_mirkan_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mirkan',
            name='isim',
            field=models.CharField(default='Kastamonulu', max_length=200),
        ),
    ]
