# Generated by Django 2.0 on 2017-12-31 03:28

from django.db import migrations, models
import shorterner.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shorterner', '0006_auto_20171228_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kirrurl',
            name='url',
            field=models.CharField(max_length=200, validators=[shorterner.validators.validate_url, shorterner.validators.validate_dot_com]),
        ),
    ]
