# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-03 00:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorterner', '0007_auto_20171231_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mirkan',
            name='isim',
            field=models.CharField(default='Kastamonu', max_length=200),
        ),
    ]
